### ISSUE TITLE
Standardized documentation for image

### ISSUE THREAD

**Issue by hhorak** [projectatomic/container-best-practices#38]
RHSCL images already use this practice: When image is run with command `container-usage`, it prints usage message.

```
$> sudo docker run <image> container-usage
This image provides....

Basic usage:
   docker run <image> -e MYVAR=variable

More information at http://...
```

We should document this and enforce it in all images.

**Comment by baude** [comment]
Hi @hhorak ,

A while back we implemented an atomic help feature similar to this.  It is described here -> http://docs.projectatomic.io/container-best-practices/#_creating_a_help_file
and http://docs.projectatomic.io/container-best-practices/#help

It is basically the same idea.  And this can be controlled with the HELP label, where you can override the behaviour defined there with exactly what you are suggesting above.  So we preserved that functionality too.

**Comment by dirkherrmann** [comment]
I definitely like the idea of the atomic help command but we need to ensure that the data inside is the same metadata we want to reuse in different other output destinations. I've added it to my trello board as an RFE for our Rel Eng tool chain automation proposal.

**Comment by eliskasl** [comment]
@hhorak I'm closing this one. Just added a bit about the default usage CMD you use in s2i images and we already have a big chapter on atomic help as well.
