### ISSUE TITLE
Emphasize that content is very important in container and that containers are not VM

### ISSUE THREAD

**Issue by hhorak** [projectatomic/container-best-practices#64]
When talking about containers, content is a very important thing. The content is important especially when we compare linux container technology with classic virtual machine. Both is kind of a type of virtualization, where we want to isolate separate applications, often called as microservices, but we cannot consider containers the same as virtual machines.

The big difference between linux containers and virtual machine is the guest's operating system, that is entirely missing in containers scenery, because all containers share the kernel with the host.

That makes the containers much more efficient, but the fact that the kernel is shared with the host means, that some unfortunate security flaw in the host kernel creates potential door from the container, which may influence either other containers or the host itself.

**Comment by baude** [comment]
@hhorak would you mind turning your issue into a pull request?
