### ISSUE TITLE
Create as small images as possible

### ISSUE THREAD

**Issue by hhorak** [projectatomic/container-best-practices#66]
For making containers small, we can use several tricks. One trick is not to install documentation:

```
RUN yum -y --setopt=tsflags=nodocs install postgresql-server
```

Another trick is to clean the cache, that yum used during the install, because that one might be quite big:

```
RUN yum -y --setopt=tsflags=nodocs install postgresql-server && yum clean all
```

We should also always create images from scratch and not updating existing images, because by adding more layers on top, we just make the container image bigger.

**Comment by baude** [comment]
Did you happen to see ->  https://github.com/projectatomic/container-best-practices/blob/master/creating/creating_index.adoc#create-small-and-concise-images 

And if so, did it not provide what you wanted?

**Comment by hhorak** [comment]
I must have overlooked it, that text is good, closing this issue..
