### ISSUE TITLE
It's Docker Save/Load, not Export/Import

### ISSUE THREAD

**Issue by fatherlinux** [projectatomic/container-best-practices#67]
Export/Import is for running containers. Save/Load is for images, which is what I think you want...

**Comment by baude** [comment]
can you provide a link to the content you are referring to?

**Comment by fatherlinux** [comment]
Yeah, again sorry, here it is: https://github.com/projectatomic/container-best-practices/blob/master/creating/creating_index.adoc

Also, here is the upstream docs:

https://docs.docker.com/engine/reference/commandline/save/

**Comment by baude** [comment]
Fixed in https://github.com/projectatomic/container-best-practices/commit/cf5613eb399b5b6b0529235097b7a78bf76c5c50 

Thanks for taking the time to help us improve documentation.
